spring:
  application:
    name: System
  datasource:
    url: jdbc:mysql://localhost:3306/frist_initializr?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT #配置数据库连接路径
    username: frist_initializr
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver #配置数据库驱动




server:
  port: 9001
  servlet:
    context-path: /System
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#指定mybatis  mapper 解析路径
mybatis:
  type-aliases-package: com.young.system.domain
  mapper-locations: classpath:mapper/*.xml
