spring:
  application:
    name: eureka
#  mvc:
#    servlet:
#      load-on-startup: 100
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false #由于Eureka项目是注册中心所以，不需要进行注册，将register-with-eureka 设置成 false ; fetch-registry 设置成 false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/